// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type DownloadJobResp struct {
	Url string `json:"url"` // 压缩包下载地址
}

type KIntVStr struct {
	K int    `json:"k"`
	V string `json:"v"`
}

type Pager struct {
	PageIndex int `json:"page_index,default=1"` // 分页
	PageSize  int `json:"page_size,default=10"` // 分页
}

type PagerForm struct {
	PageIndex int `form:"page_index,default=1"` // 分页
	PageSize  int `form:"page_size,default=10"` // 分页
}

type PasswdPair struct {
	OldPasswd string `json:"old_passwd,optional" zh_Hans_CN:"旧密码" validate:"required"` // 旧密码
	NewPasswd string `json:"new_passwd,optional" zh_Hans_CN:"新密码" validate:"required"` // 新密码
}

type TimeRange struct {
	Start int64 `json:"start_time" zh_Hans_CN:"开始时间" validate:"gt=0"`         // 时间辍, 秒
	Stop  int64 `json:"stop_time" zh_Hans_CN:"结束时间" validate:"gtfield=Start"` // 时间辍, 秒
}

type TimeRangeForm struct {
	Start int64 `form:"start_time" zh_Hans_CN:"开始时间" validate:"gt=0"`         // 时间辍, 秒
	Stop  int64 `form:"stop_time" zh_Hans_CN:"结束时间" validate:"gtfield=Start"` // 时间辍, 秒
}

type UpperLower struct {
	Upper *float64 `json:"upper"` // 上限
	Lower *float64 `json:"lower"` // 下限
}
