// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package handler

import (
	"net/http"

	job "cayoyibackend/internal/handler/job"
	user "cayoyibackend/internal/handler/user"
	"cayoyibackend/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 作业文件下载
				Method:  http.MethodPost,
				Path:    "/download/jobs",
				Handler: job.DownloadJobsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/job"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 用户登录
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				// 获取 RSA 加密公钥
				Method:  http.MethodGet,
				Path:    "/pubkey",
				Handler: user.GetPubKeyHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/user"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 用户信息
				Method:  http.MethodGet,
				Path:    "/",
				Handler: user.GetUserHandler(serverCtx),
			},
			{
				// 用户信息修改
				Method:  http.MethodPost,
				Path:    "/",
				Handler: user.UpdateUserHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/user"),
	)
}
